/**
 * 
 */
/**
 * 
 */
module labassessment {
}

Installing Docker on windows
1.open https://docs.docker.com/docker-for-windows/install
2.Download the latest version and install it.
3.To execute docker commands in windows
 -->open powershell (in windows like dos)
 -->run the docker commands
Note:
Docker for windows can be installed only on windows10 prof x24 bit
 (or)
 windows 2016 server edition
Docker images
an image is a collection of bin/lib(binaries/libraries)that are necessary for an application
Docker Container
-->a running instance of an image is called as a container
--> any number of containers can be created from one image
-->initially all the docker images are present in the cloudsite of docker(hub.docker.com)
Docker Client
--> this is the application where we can fire the docker commands.the Linux terminal will act as a
docker client
--> the docker client will take the commands and send them to a background process called
dockerdaemon.
DockerDaemon
This is a background process of docker which runs in the dockerdaemon
and it will accept the commands coming from dockerclient and send them to docker images (oR)
containers (or) the docker registry.
Docker Registry
docker registry is the cloud site of docker where all the docker images are present.
this is two types
 1.public
 2.private
1.public Registery
 public Registery is hub.docker.com and anyone can download images from this site.
2.private Registery
 private Registery is maintained by individual organizations and only the organization team members
can access these images.
The machine where docker is installed and where all the containers are running is called "Docker
Host".
Important Docker commands
Working on dockerImages
1. To see the list of docker images in our machine(DockerHost)
 >>docker images
 (or)
 >> docker image ls
2. To download an image from docker hub

 >> docker pull image-name
3.To upload an image into dockerhub
>> docker push image-name
4. To search for an images on docker hub
 >> docker search image-name
5. To delete an image on docker host
>> docker rmi image-name
6. To create an image from a container
>> docker commit container-name/container-id image-name
7. To create an image from a dockerfile
 >> docker build -t imagename .
Note
 . represents current working directory
Working on docker containers
8.To see the list of running containers
>> docker container ls
9.To see the list of stopped and running containers
>> docker ps -a
10. To start a container
>> docker start container-name/container-id
11. To stop a container
>> docker stop container-name/container-id
12. To restart a container
>> docker restart container-name/container-id
 To restart a container after 10 seconds
>> docker restart -t 10 container-name/container-id
13. To remove a stopped container
>> docker rm container-name/container-id
14. To remove a running container
>> docker rm -f container-name/container-id
15. To stop all the running containers
>>docker stop $(docker ps -aq)
16. To remove all the stopped containers
>>docker rm $(docker ps -aq)
17. To remove all the running containers
>>docker rm $(docker ps -aq)
18. To see the logs generated by the container
>> docker logs container-name/container-id
19. To see the ports of a container
>> docker port container-name/container-id
20. To find detailed info about a container
>> docker inspect container-name/container-id
21.creating a docker container
>> docker run image-name
22.To see the list of docker networking
>>docker network ls
23.To inspect a network
>> docker network inspect network-id/network-name
24.To create a network
>> docker network create network-name
25.To delete a network
>> docker network rm create network-id/network-name
